title: / # your site title
author: Dimas Setya Aji
email: dimasetyaaji@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Update anime terbaru dan menarik.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://d3f4lt.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dimasetyaji # replace with your_twitter_username or comment to remove link from footer
github_username:  D3f4lt # replace with your_github_username or comment to remove link from footer
instagram_username: dimas_cyber4rt # replace with your_instagram_username or comment to remove link from footer
social:
  name: Animepediaku
  links:
    - https://twitter.com/dimasetyaji
    - https://www.facebook.com/dimassetyaaji
    - https://plus.google.com/+dimasetyaaji
    - https://github.com/d3f4lt

disqus:
  shortname: animepediaku # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 3
