title: Animepediaku
author: Dimas Setya Aji
description: > 
  Situs yang menampilkan seputar dunia anime terkini, menarik, dan juga membahas hal-hal internet lainnya.
baseurl: "/animepediaku" 
url: "https://d3f4lt.github.io/" 
 
social:
  name: Animepediaku
  links:
    - https://twitter.com/dimasetyaji
    - https://www.facebook.com/dimassetyaaji
    - https://plus.google.com/+dimasetyaaji
    - https://github.com/d3f4lt
    
# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Beranda', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Kontak', link: '/contact'}

tagline: >
  Situs yang menampilkan seputar dunia anime terkini, menarik, dan juga membahas hal-hal internet lainnya.

hero_img: posts/sleek_lg.jpg

email: dimasetyaaji@gmail.com 
twitter_username: dimasetyaji 
github_username:  D3f4lt 
instagram_username: dimas_cyber4rt

disqus:
  shortname: animepediaku # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 3
